using System;
using InputLog.Core.Util;

namespace InputLog.Core.Hooks
{
    /// <summary>
    /// This class listens to the eventz generated by Windows.
    /// </summary>
    public abstract class WindowsEventListener : IDisposable
    {
        #region Fields

        /// <summary>
        /// Reference to the callback that is installed.
        /// </summary>
        private readonly WindowsHook hook;

        /// <summary>
        /// Handler of the registered hook.
        /// </summary>
        private IntPtr HookHandler;

        /// <summary>
        /// True if the object is disposed, false if not.
        /// </summary>
        protected bool Disposed { get; private set; }

        #endregion

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="idHook">The id of the hook where the callack method of the instance should be registered to.</param>
        internal WindowsEventListener(int idHook)
        {
            hook = Callback;
            HookHandler = NativeMethods.SetWindowsHookEx(idHook, hook, NativeMethods.DllHandle, 0);
            Disposed = false;
        }

        #region IDisposable Members

        /// <summary>
        /// Disposes the object.
        /// </summary>
        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        #endregion

        /// <summary>
        /// General implementation of the callback function.
        /// Takes care of CallNextHookEx and calls finishEvent for further processing.
        /// See http://msdn.microsoft.com/en-us/library/ms644990.aspx for further information.
        /// </summary>
        /// <param name="nCode">nCode as passed by Windows to callback.</param>
        /// <param name="wParam">wParam as passed by Windows to callback.</param>
        /// <param name="lParam">lParam as passed by Windows to callback.</param>
        /// <returns>The value returned by CallNextHook.</returns>
        private IntPtr Callback(int nCode, IntPtr wParam, IntPtr lParam)
        {
            if (nCode < 0)
            {
                return NativeMethods.CallNextHookEx(HookHandler, nCode, wParam, lParam);
            }
            try
            {
                ProcessEvent(nCode, wParam, lParam);
            }
            catch (Exception e)
            {
                MessageLogger.CatchException(this, e, Severity.ERROR);
            }
            return NativeMethods.CallNextHookEx(NativeMethods.DllHandle, nCode, wParam, lParam);
        }

        /// <summary>
        /// Subclasses should implement this method and take care of the actual processing
        /// (and possibly notifying of any registered listeners). The parameters are the paremeters
        /// passed to the callback method.
        /// </summary>
        /// <param name="nCode">nCode as passed by Windows to callback.</param>
        /// <param name="wParam">wParam as passed by Windows to callback.</param>
        /// <param name="lParam">lParam as passed by Windows to callback.</param>
        protected abstract void ProcessEvent(int nCode, IntPtr wParam, IntPtr lParam);

        /// <summary>
        /// Disposes the object.
        /// </summary>
        /// <param name="disposing">True if the managed resources should also be disposed, false if not.</param>
        protected virtual void Dispose(bool disposing)
        {
            if (!Disposed)
            {
                NativeMethods.UnhookWindowsHookEx(HookHandler);
                HookHandler = IntPtr.Zero;

                Disposed = true;
            }
        }

        /// <summary>
        /// Destructor.
        /// </summary>
        ~WindowsEventListener()
        {
            Dispose(false);
        }
    }
}