//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputLog.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InputLog.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CC_Image {
            get {
                object obj = ResourceManager.GetObject("CC_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /**
        /// * common.css
        /// * Stylesheet containing common styles for InputLog Analyses.
        /// */
        ///body
        ///{
        ///    background-color: #F7F7F7;
        ///    font-family: verdana;
        ///    color: #333366;
        ///    font-size: 11px;
        ///}
        ///
        ///abbr
        ///{
        ///    border-bottom: 1px dotted;
        ///}
        ///
        ///hr
        ///{
        ///    border: 0px;
        ///    color: #333366;
        ///    background-color: #333366;
        ///    height: 1px;
        ///}
        ///
        ///h1
        ///{
        ///    color: #993300;
        ///    font-size: 18px;
        ///    font-weight: bold;
        ///}
        ///
        ///h2
        ///{
        ///    color: #993300;
        ///    font-size: 12px;
        ///    font-weight: bold;
        ///    floa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commonCSS {
            get {
                return ResourceManager.GetString("commonCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; version=&quot;4.0&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!-- Header of the Analysis document --&gt;
        ///  &lt;xsl:template name=&quot;header&quot;&gt;
        ///    &lt;div id=&quot;header&quot;&gt;
        ///      &lt;img src=&quot;images/InputLog-Logo.gif&quot; alt=&quot;InputLog logo&quot; class=&quot;logo&quot;/&gt;
        ///      &lt;br class=&quot;clear&quot; /&gt;
        ///    &lt;/div&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!-- Displays meta and sessionidentication information in a table --&gt;
        ///  &lt;xsl:template name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string commonXSL {
            get {
                return ResourceManager.GetString("commonXSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///	&lt;xsl:include href=&quot;common.xsl&quot; /&gt;
        ///	&lt;xsl:template match=&quot;/&quot;&gt;
        ///		&lt;html&gt;
        ///			&lt;head&gt;
        ///				&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style/common.css&quot; /&gt;
        ///				&lt;title&gt;General Analysis&lt;/title&gt;
        ///				&lt;style&gt;
        ///					.windowTitle div{
        ///					border: 1px solid #E9EEF3;
        ///					padding:2px 5px;
        ///					margin-left: 5px;
        ///					background-color: #ffffdd;
        ///					position:absolute;
        ///					display:none;
        ///				 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string general_analysis {
            get {
                return ResourceManager.GetString("general_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] iconv {
            get {
                object obj = ResourceManager.GetObject("iconv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap InputLog_Logo {
            get {
                object obj = ResourceManager.GetObject("InputLog_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Integrate {
            get {
                object obj = ResourceManager.GetObject("Integrate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.4.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Sat Feb 13 22:33:48 2010 -0500
        /// */
        ///(function(A,w){function ma(){if(!c.isReady){try{s.documentElement.doScroll(&quot;left&quot;)}catch(a){setTimeout(ma,1);return}c.ready()}}fun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_1_4_2_min {
            get {
                return ResourceManager.GetString("jquery_1_4_2_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libiconv2 {
            get {
                object obj = ResourceManager.GetObject("libiconv2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] libxml2 {
            get {
                object obj = ResourceManager.GetObject("libxml2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:include href=&quot;common.xsl&quot; /&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;title&gt;Linear Analysis&lt;/title&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style/common.css&quot; /&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///
        ///        &lt;!-- Header and sessionidentification --&gt;
        ///        &lt;xsl:call-template name=&quot;header&quot; /&gt;
        ///        &lt;h1&gt;Linear Logging File&lt;/h1&gt;
        ///        &lt;xsl:call-te [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string linear_analysis {
            get {
                return ResourceManager.GetString("linear_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:include href=&quot;common.xsl&quot; /&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style/common.css&quot; /&gt;
        ///        &lt;title&gt;Pause Analysis&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///
        ///        &lt;!-- Header and sessionidentification --&gt;
        ///        &lt;xsl:call-template name=&quot;header&quot; /&gt;
        ///        &lt;h1&gt;Pause Logging File&lt;/h1&gt;
        ///        &lt;xsl:call-temp [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pause_analysis {
            get {
                return ResourceManager.GetString("pause_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        ///  &lt;xsl:include href=&quot;common.xsl&quot; /&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;Style/common.css&quot; /&gt;
        ///        &lt;title&gt;Summary Analysis&lt;/title&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///
        ///        &lt;!-- Header and sessionidentification --&gt;
        ///        &lt;xsl:call-template name=&quot;header&quot; /&gt;
        ///        &lt;h1&gt;Summary Logging File&lt;/h1&gt;
        ///        &lt;xsl:call- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string summary_analysis {
            get {
                return ResourceManager.GetString("summary_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zlib1 {
            get {
                object obj = ResourceManager.GetObject("zlib1", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
