//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputLog.Core.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Stop_Timeout {
            get {
                return ((int)(this["Stop_Timeout"]));
            }
            set {
                this["Stop_Timeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WordLog_OverrideDoc {
            get {
                return ((bool)(this["WordLog_OverrideDoc"]));
            }
            set {
                this["WordLog_OverrideDoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public ulong WinLog_MouseMovementPauseThreshold {
            get {
                return ((ulong)(this["WinLog_MouseMovementPauseThreshold"]));
            }
            set {
                this["WinLog_MouseMovementPauseThreshold"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Legacy\\Integrate.exe")]
        public string Integrate_exe {
            get {
                return ((string)(this["Integrate_exe"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WordLog_DisableWordAddins {
            get {
                return ((bool)(this["WordLog_DisableWordAddins"]));
            }
            set {
                this["WordLog_DisableWordAddins"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong Analysis_DoubleClickThreshold {
            get {
                return ((ulong)(this["Analysis_DoubleClickThreshold"]));
            }
            set {
                this["Analysis_DoubleClickThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WinLog_Restricted {
            get {
                return ((bool)(this["WinLog_Restricted"]));
            }
            set {
                this["WinLog_Restricted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Segmentation_KeyDelimiterIsActive {
            get {
                return ((bool)(this["Segmentation_KeyDelimiterIsActive"]));
            }
            set {
                this["Segmentation_KeyDelimiterIsActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Segmentation_KeyDelimiter {
            get {
                return ((string)(this["Segmentation_KeyDelimiter"]));
            }
            set {
                this["Segmentation_KeyDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Segmentation_IncludeInitialPause {
            get {
                return ((bool)(this["Segmentation_IncludeInitialPause"]));
            }
            set {
                this["Segmentation_IncludeInitialPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong TimebasedIntervalSave {
            get {
                return ((ulong)(this["TimebasedIntervalSave"]));
            }
            set {
                this["TimebasedIntervalSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AddComment {
            get {
                return ((bool)(this["AddComment"]));
            }
            set {
                this["AddComment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserActionIntervalSave {
            get {
                return ((string)(this["UserActionIntervalSave"]));
            }
            set {
                this["UserActionIntervalSave"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://lt3serv.ugent.be:80/PreProService/PreProWS")]
        public string InputLogCore_be_ugent_lt3serv_PreProWS {
            get {
                return ((string)(this["InputLogCore_be_ugent_lt3serv_PreProWS"]));
            }
        }
    }
}
