// This code was generated by the Gardens Point Parser Generator
// Copyright (c) Wayne Kelly, QUT 2005-2010
// (see accompanying GPPGcopyright.rtf)

// GPPG version 1.5.0
// Machine:  LAPTOP-18LAJ41M
// DateTime: 20/01/2020 21:37:02
// UserName: ASUS
// Input file <Parser.y - 20/01/2020 21:25:19>

// options: lines report gplex

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using QUT.Gppg;
using InputLog.Core.Analyses;
using InputLog.Core.Util;

namespace InputLog.Core.Analyses.PauseParser
{
public enum Tokens {
    error=1,EOF=2,COMMENT=3,IDENTIFIER=4,DOLLAR=5,COMMA=6,
    HASH=7,COLON=8,SEMICOLON=9,ARROW=10,NUMBER=11,LPAR=12,
    RPAR=13,STAR=14,LBRACK=15,RBRACK=16,LBRACE=17,RBRACE=18,
    LANGLE=19,RANGLE=20,PIPE=21,PERIOD=22,EXCL=23,QST=24,
    PLUS=25,MINUS=26,EOL=27};

public struct ValueType
#line 19 "Parser.y"
{
#line 20 "Parser.y"
	public string String;//Otherwise error on "string" being a keyword
#line 21 "Parser.y"
	public bool Bool;//Otherwise error on "bool" being a keyword
#line 22 "Parser.y"
	public int Int;//Otherwise error on "int" being a keyword
#line 23 "Parser.y"
    public List<string> Stringlist;
#line 24 "Parser.y"
	public List<Triple<string,bool,int>> Stringboolintlist;
#line 25 "Parser.y"
	public ARegexRule<string> Ruletype;
#line 26 "Parser.y"
}
// Abstract base class for GPLEX scanners
public abstract class ScanBase : AbstractScanner<ValueType,LexLocation> {
  private LexLocation __yylloc = new LexLocation();
  public override LexLocation yylloc { get { return __yylloc; } set { __yylloc = value; } }
  protected virtual bool yywrap() { return true; }
}

// Utility class for encapsulating token information
public class ScanObj {
  public int token;
  public ValueType yylval;
  public LexLocation yylloc;
  public ScanObj( int t, ValueType val, LexLocation loc ) {
    this.token = t; this.yylval = val; this.yylloc = loc;
  }
}

public class Parser: ShiftReduceParser<ValueType, LexLocation>
{
  // Verbatim content from Parser.y - 20/01/2020 21:25:19
#line 9 "Parser.y"
	private AFSMFactory<string> factory;
#line 10 "Parser.y"
	private IRuleFactory<string> ruleFactory;
#line 11 "Parser.y"
	private List<ARegexRule<string>> ruleSet;
#line 12 "Parser.y"

  // End verbatim content from Parser.y - 20/01/2020 21:25:19

#pragma warning disable 649
  private static Dictionary<int, string> aliasses;
#pragma warning restore 649
  private static Rule[] rules = new Rule[26];
  private static State[] states = new State[46];
  private static string[] nonTerms = new string[] {
      "fsmstart", "identlist", "identlist2", "eventinverse", "eventpeek", "eventlist", 
      "eventlist2", "actionlist", "rule", "compoundRule", "$accept", "rulelist", 
      "ruleend", };

  static Parser() {
    states[0] = new State(new int[]{12,8,23,41,4,-12,2,-5},new int[]{-1,1,-12,3,-9,4,-10,7,-6,33,-4,35});
    states[1] = new State(new int[]{2,2});
    states[2] = new State(-1);
    states[3] = new State(-2);
    states[4] = new State(new int[]{14,19,25,21,15,23,22,27,21,30,9,45},new int[]{-13,5});
    states[5] = new State(new int[]{12,8,23,41,4,-12,2,-5},new int[]{-12,6,-9,4,-10,7,-6,33,-4,35});
    states[6] = new State(-4);
    states[7] = new State(-18);
    states[8] = new State(new int[]{12,8,23,41,4,-12},new int[]{-9,9,-10,7,-6,33,-4,35});
    states[9] = new State(new int[]{13,10,14,19,25,21,15,23,22,27,21,30});
    states[10] = new State(new int[]{17,12,14,-10,25,-10,15,-10,22,-10,21,-10,9,-10,13,-10},new int[]{-8,11});
    states[11] = new State(-20);
    states[12] = new State(new int[]{4,15},new int[]{-2,13});
    states[13] = new State(new int[]{18,14});
    states[14] = new State(-9);
    states[15] = new State(new int[]{6,17,18,-8},new int[]{-3,16});
    states[16] = new State(-6);
    states[17] = new State(new int[]{4,15},new int[]{-2,18});
    states[18] = new State(-7);
    states[19] = new State(new int[]{17,12,14,-10,25,-10,15,-10,22,-10,21,-10,9,-10,13,-10},new int[]{-8,20});
    states[20] = new State(-21);
    states[21] = new State(new int[]{17,12,14,-10,25,-10,15,-10,22,-10,21,-10,9,-10,13,-10},new int[]{-8,22});
    states[22] = new State(-22);
    states[23] = new State(new int[]{11,24});
    states[24] = new State(new int[]{16,25});
    states[25] = new State(new int[]{17,12,14,-10,25,-10,15,-10,22,-10,21,-10,9,-10,13,-10},new int[]{-8,26});
    states[26] = new State(-23);
    states[27] = new State(new int[]{12,8,23,41,4,-12},new int[]{-9,28,-10,7,-6,33,-4,35});
    states[28] = new State(new int[]{14,19,25,21,15,23,22,27,21,30,17,12,9,-10,13,-10},new int[]{-8,29});
    states[29] = new State(-24);
    states[30] = new State(new int[]{12,8,23,41,4,-12},new int[]{-9,31,-10,7,-6,33,-4,35});
    states[31] = new State(new int[]{14,19,25,21,15,23,22,27,21,30,17,12,9,-10,13,-10},new int[]{-8,32});
    states[32] = new State(-25);
    states[33] = new State(new int[]{17,12,14,-10,25,-10,15,-10,22,-10,21,-10,9,-10,13,-10},new int[]{-8,34});
    states[34] = new State(-19);
    states[35] = new State(new int[]{4,36});
    states[36] = new State(new int[]{19,42,6,-14,17,-14,14,-14,25,-14,15,-14,22,-14,21,-14,9,-14,13,-14},new int[]{-5,37});
    states[37] = new State(new int[]{6,39,17,-17,14,-17,25,-17,15,-17,22,-17,21,-17,9,-17,13,-17},new int[]{-7,38});
    states[38] = new State(-15);
    states[39] = new State(new int[]{23,41,4,-12},new int[]{-6,40,-4,35});
    states[40] = new State(-16);
    states[41] = new State(-11);
    states[42] = new State(new int[]{11,43});
    states[43] = new State(new int[]{20,44});
    states[44] = new State(-13);
    states[45] = new State(-3);

    for (int sNo = 0; sNo < states.Length; sNo++) states[sNo].number = sNo;

    rules[1] = new Rule(-11, new int[]{-1,2});
    rules[2] = new Rule(-1, new int[]{-12});
    rules[3] = new Rule(-13, new int[]{9});
    rules[4] = new Rule(-12, new int[]{-9,-13,-12});
    rules[5] = new Rule(-12, new int[]{});
    rules[6] = new Rule(-2, new int[]{4,-3});
    rules[7] = new Rule(-3, new int[]{6,-2});
    rules[8] = new Rule(-3, new int[]{});
    rules[9] = new Rule(-8, new int[]{17,-2,18});
    rules[10] = new Rule(-8, new int[]{});
    rules[11] = new Rule(-4, new int[]{23});
    rules[12] = new Rule(-4, new int[]{});
    rules[13] = new Rule(-5, new int[]{19,11,20});
    rules[14] = new Rule(-5, new int[]{});
    rules[15] = new Rule(-6, new int[]{-4,4,-5,-7});
    rules[16] = new Rule(-7, new int[]{6,-6});
    rules[17] = new Rule(-7, new int[]{});
    rules[18] = new Rule(-9, new int[]{-10});
    rules[19] = new Rule(-9, new int[]{-6,-8});
    rules[20] = new Rule(-10, new int[]{12,-9,13,-8});
    rules[21] = new Rule(-10, new int[]{-9,14,-8});
    rules[22] = new Rule(-10, new int[]{-9,25,-8});
    rules[23] = new Rule(-10, new int[]{-9,15,11,16,-8});
    rules[24] = new Rule(-10, new int[]{-9,22,-9,-8});
    rules[25] = new Rule(-10, new int[]{-9,21,-9,-8});
  }

  protected override void Initialize() {
    this.InitSpecialTokens((int)Tokens.error, (int)Tokens.EOF);
    this.InitStates(states);
    this.InitRules(rules);
    this.InitNonTerminals(nonTerms);
  }

  protected override void DoAction(int action)
  {
#pragma warning disable 162, 1522
    switch (action)
    {
      case 4: // rulelist -> rule, ruleend, rulelist
#line 77 "Parser.y"
{
#line 78 "Parser.y"
						ruleSet.Insert(0, ValueStack[ValueStack.Depth-3].Ruletype); 
#line 79 "Parser.y"
					}
        break;
      case 5: // rulelist -> /* empty */
#line 82 "Parser.y"
{
#line 83 "Parser.y"
						//Do nothing
					}
        break;
      case 6: // identlist -> IDENTIFIER, identlist2
#line 88 "Parser.y"
{ValueStack[ValueStack.Depth-1].Stringlist.Insert(0, ValueStack[ValueStack.Depth-2].String);}
        break;
      case 7: // identlist2 -> COMMA, identlist
#line 92 "Parser.y"
{
#line 93 "Parser.y"
						CurrentSemanticValue.Stringlist = ValueStack[ValueStack.Depth-1].Stringlist;
#line 94 "Parser.y"
					}
        break;
      case 8: // identlist2 -> /* empty */
#line 97 "Parser.y"
{
#line 98 "Parser.y"
						CurrentSemanticValue.Stringlist = new List<string>();
#line 99 "Parser.y"
					}
        break;
      case 9: // actionlist -> LBRACE, identlist, RBRACE
#line 104 "Parser.y"
{
#line 105 "Parser.y"
						CurrentSemanticValue.Stringlist = ValueStack[ValueStack.Depth-2].Stringlist;
#line 106 "Parser.y"
					}
        break;
      case 10: // actionlist -> /* empty */
#line 109 "Parser.y"
{
#line 110 "Parser.y"
						CurrentSemanticValue.Stringlist = new List<string>();
#line 111 "Parser.y"
					}
        break;
      case 11: // eventinverse -> EXCL
#line 115 "Parser.y"
{ 
#line 116 "Parser.y"
						CurrentSemanticValue.Bool = true;
#line 117 "Parser.y"
					}
        break;
      case 12: // eventinverse -> /* empty */
#line 120 "Parser.y"
{ 
#line 121 "Parser.y"
						CurrentSemanticValue.Bool = false;
#line 122 "Parser.y"
					}
        break;
      case 13: // eventpeek -> LANGLE, NUMBER, RANGLE
#line 126 "Parser.y"
{ 
#line 127 "Parser.y"
						CurrentSemanticValue.Int = int.Parse(ValueStack[ValueStack.Depth-2].String);
#line 128 "Parser.y"
					}
        break;
      case 14: // eventpeek -> /* empty */
#line 131 "Parser.y"
{ 
#line 132 "Parser.y"
						CurrentSemanticValue.Int = 0;
#line 133 "Parser.y"
					}
        break;
      case 15: // eventlist -> eventinverse, IDENTIFIER, eventpeek, eventlist2
#line 137 "Parser.y"
{
#line 138 "Parser.y"
						ValueStack[ValueStack.Depth-1].Stringboolintlist.Insert(0, new Triple<string,bool, int>(ValueStack[ValueStack.Depth-3].String, ValueStack[ValueStack.Depth-4].Bool, ValueStack[ValueStack.Depth-2].Int));
#line 139 "Parser.y"
					}
        break;
      case 16: // eventlist2 -> COMMA, eventlist
#line 143 "Parser.y"
{
#line 144 "Parser.y"
						CurrentSemanticValue.Stringboolintlist = ValueStack[ValueStack.Depth-1].Stringboolintlist;
#line 145 "Parser.y"
					}
        break;
      case 17: // eventlist2 -> /* empty */
#line 148 "Parser.y"
{
#line 149 "Parser.y"
						CurrentSemanticValue.Stringboolintlist = new List<Triple<string,bool,int>>();
#line 150 "Parser.y"
					}
        break;
      case 18: // rule -> compoundRule
#line 155 "Parser.y"
{
#line 156 "Parser.y"
						CurrentSemanticValue.Ruletype = ValueStack[ValueStack.Depth-1].Ruletype;
#line 157 "Parser.y"
					}
        break;
      case 19: // rule -> eventlist, actionlist
#line 161 "Parser.y"
{
#line 162 "Parser.y"
						CurrentSemanticValue.Ruletype = ruleFactory.MakeSymbolRule(ValueStack[ValueStack.Depth-2].Stringboolintlist, ValueStack[ValueStack.Depth-1].Stringlist);
#line 163 "Parser.y"
					}
        break;
      case 20: // compoundRule -> LPAR, rule, RPAR, actionlist
#line 168 "Parser.y"
{
#line 169 "Parser.y"
							CurrentSemanticValue.Ruletype = ruleFactory.MakeParenthesesRule(ValueStack[ValueStack.Depth-3].Ruletype, ValueStack[ValueStack.Depth-1].Stringlist);
#line 170 "Parser.y"
						}
        break;
      case 21: // compoundRule -> rule, STAR, actionlist
#line 173 "Parser.y"
{
#line 174 "Parser.y"
							CurrentSemanticValue.Ruletype = ruleFactory.MakeKleeneStarRule(ValueStack[ValueStack.Depth-3].Ruletype, ValueStack[ValueStack.Depth-1].Stringlist);
#line 175 "Parser.y"
						}
        break;
      case 22: // compoundRule -> rule, PLUS, actionlist
#line 178 "Parser.y"
{
#line 179 "Parser.y"
							CurrentSemanticValue.Ruletype = ruleFactory.MakePlusRule(ValueStack[ValueStack.Depth-3].Ruletype, ValueStack[ValueStack.Depth-1].Stringlist);
#line 180 "Parser.y"
						}
        break;
      case 23: // compoundRule -> rule, LBRACK, NUMBER, RBRACK, actionlist
#line 183 "Parser.y"
{
#line 184 "Parser.y"
							int times = int.Parse(ValueStack[ValueStack.Depth-3].String);
#line 185 "Parser.y"
							CurrentSemanticValue.Ruletype = ruleFactory.MakeNumberRule(ValueStack[ValueStack.Depth-5].Ruletype, times, ValueStack[ValueStack.Depth-1].Stringlist);
#line 186 "Parser.y"
						}
        break;
      case 24: // compoundRule -> rule, PERIOD, rule, actionlist
#line 190 "Parser.y"
{
#line 191 "Parser.y"
							CurrentSemanticValue.Ruletype = ruleFactory.MakeConcatRule(ValueStack[ValueStack.Depth-4].Ruletype, ValueStack[ValueStack.Depth-2].Ruletype, ValueStack[ValueStack.Depth-1].Stringlist);
#line 192 "Parser.y"
						}
        break;
      case 25: // compoundRule -> rule, PIPE, rule, actionlist
#line 195 "Parser.y"
{
#line 196 "Parser.y"
							CurrentSemanticValue.Ruletype = ruleFactory.MakeUnionRule(ValueStack[ValueStack.Depth-4].Ruletype, ValueStack[ValueStack.Depth-2].Ruletype, ValueStack[ValueStack.Depth-1].Stringlist);
#line 197 "Parser.y"
						}
        break;
    }
#pragma warning restore 162, 1522
  }

  protected override string TerminalToString(int terminal)
  {
    if (aliasses != null && aliasses.ContainsKey(terminal))
        return aliasses[terminal];
    else if (((Tokens)terminal).ToString() != terminal.ToString(CultureInfo.InvariantCulture))
        return ((Tokens)terminal).ToString();
    else
        return CharToString((char)terminal);
  }

#line 202 "Parser.y"
/// <summary>
#line 203 "Parser.y"
/// Constructor
#line 204 "Parser.y"
/// </summary>
#line 205 "Parser.y"
/// <param name="scn">Scanner processing the file</param>
#line 206 "Parser.y"
/// <param name="factory">Factory to build the finite state machine</param>
#line 207 "Parser.y"
/// <param name="ruleFactory">Factory to build the rules</param>
#line 208 "Parser.y"
public Parser(Scanner scn, AFSMFactory<string> factory, IRuleFactory<string> ruleFactory) : base(scn) 
#line 209 "Parser.y"
{
#line 210 "Parser.y"
	this.factory = factory;
#line 211 "Parser.y"
	this.ruleFactory = ruleFactory;
#line 212 "Parser.y"
	this.ruleSet =  new List<ARegexRule<string>>();
#line 213 "Parser.y"
}
#line 214 "Parser.y"

#line 215 "Parser.y"
/// <summary>
#line 216 "Parser.y"
/// Returns the NFAs that were read by this parser
#line 217 "Parser.y"
/// </summary>
#line 218 "Parser.y"
///<returns>A list of epsilon non-deterministic finite automata, as they were read from file</returns>
#line 219 "Parser.y"
public List<NonDeterministicFiniteStateMachine<string>> GetNonDeterministicFiniteStateMachines()
#line 220 "Parser.y"
{
#line 221 "Parser.y"
	List<NonDeterministicFiniteStateMachine<string>> enfsmList = new List<NonDeterministicFiniteStateMachine<string>>();
#line 222 "Parser.y"
	
#line 223 "Parser.y"
	this.Parse();
#line 224 "Parser.y"

#line 225 "Parser.y"
	foreach(ARegexRule<string> startRule in ruleSet)
#line 226 "Parser.y"
	{
#line 227 "Parser.y"
		factory.NewFiniteStateMachine();
#line 228 "Parser.y"
		string startState = string.Empty;
#line 229 "Parser.y"
		if(startRule != null)
#line 230 "Parser.y"
		{
#line 231 "Parser.y"
			Pair<string, string> startPair = startRule.AddToFSM(factory);
#line 232 "Parser.y"
			startState = startPair.First;
#line 233 "Parser.y"
		}
#line 234 "Parser.y"
		NonDeterministicFiniteStateMachine<string> enfsm = factory.BuildFiniteStateMachine();
#line 235 "Parser.y"
		enfsm.SetStartState(startState);
#line 236 "Parser.y"
		enfsmList.Add(enfsm);
#line 237 "Parser.y"
	}
#line 238 "Parser.y"
	return enfsmList;
#line 239 "Parser.y"
}
#line 240 "Parser.y"

#line 241 "Parser.y"
/// <summary>
#line 242 "Parser.y"
/// Returns a list of DFAs, equivalent to the NFAs that were read by this parser
#line 243 "Parser.y"
/// </summary>
#line 244 "Parser.y"
///<returns>A list of deterministic finite automata</returns>
#line 245 "Parser.y"
public List<DeterministicFiniteStateMachine<ISet<string>>> GetDeterministicFiniteStateMachines()
#line 246 "Parser.y"
{
#line 247 "Parser.y"
	List<NonDeterministicFiniteStateMachine<string>> enfsmList = this.GetNonDeterministicFiniteStateMachines();
#line 248 "Parser.y"
	List<DeterministicFiniteStateMachine<ISet<string>>> dfsmList = new List<DeterministicFiniteStateMachine<ISet<string>>>();
#line 249 "Parser.y"
	foreach(NonDeterministicFiniteStateMachine<string> enfsm in enfsmList)
#line 250 "Parser.y"
	{
#line 251 "Parser.y"
		dfsmList.Add(DeterministicFiniteStateMachine<string>.ConstructDFA(enfsm));
#line 252 "Parser.y"
	}
#line 253 "Parser.y"
	return dfsmList;
#line 254 "Parser.y"
}
}
}
