//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InputLog.Core.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lt3serv.ugent.be/", ConfigurationName="ServiceReference1.PreProWS")]
    public interface PreProWS {
        
        // CODEGEN: Generating message contract since element name language from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lt3serv.ugent.be/PreProWS/submitRequest", ReplyAction="http://lt3serv.ugent.be/PreProWS/submitResponse")]
        InputLog.Core.ServiceReference1.submitResponse submit(InputLog.Core.ServiceReference1.submitRequest request);
        
        // CODEGEN: Generating message contract since element name text_id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lt3serv.ugent.be/PreProWS/checkRequest", ReplyAction="http://lt3serv.ugent.be/PreProWS/checkResponse")]
        InputLog.Core.ServiceReference1.checkResponse check(InputLog.Core.ServiceReference1.checkRequest request);
        
        // CODEGEN: Generating message contract since element name text_id from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://lt3serv.ugent.be/PreProWS/acquireRequest", ReplyAction="http://lt3serv.ugent.be/PreProWS/acquireResponse")]
        InputLog.Core.ServiceReference1.acquireResponse acquire(InputLog.Core.ServiceReference1.acquireRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submit", Namespace="http://lt3serv.ugent.be/", Order=0)]
        public InputLog.Core.ServiceReference1.submitRequestBody Body;
        
        public submitRequest() {
        }
        
        public submitRequest(InputLog.Core.ServiceReference1.submitRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class submitRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string language;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string text;
        
        public submitRequestBody() {
        }
        
        public submitRequestBody(string language, string text) {
            this.language = language;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class submitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="submitResponse", Namespace="http://lt3serv.ugent.be/", Order=0)]
        public InputLog.Core.ServiceReference1.submitResponseBody Body;
        
        public submitResponse() {
        }
        
        public submitResponse(InputLog.Core.ServiceReference1.submitResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class submitResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public submitResponseBody() {
        }
        
        public submitResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="check", Namespace="http://lt3serv.ugent.be/", Order=0)]
        public InputLog.Core.ServiceReference1.checkRequestBody Body;
        
        public checkRequest() {
        }
        
        public checkRequest(InputLog.Core.ServiceReference1.checkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text_id;
        
        public checkRequestBody() {
        }
        
        public checkRequestBody(string text_id) {
            this.text_id = text_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkResponse", Namespace="http://lt3serv.ugent.be/", Order=0)]
        public InputLog.Core.ServiceReference1.checkResponseBody Body;
        
        public checkResponse() {
        }
        
        public checkResponse(InputLog.Core.ServiceReference1.checkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class checkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public checkResponseBody() {
        }
        
        public checkResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acquireRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acquire", Namespace="http://lt3serv.ugent.be/", Order=0)]
        public InputLog.Core.ServiceReference1.acquireRequestBody Body;
        
        public acquireRequest() {
        }
        
        public acquireRequest(InputLog.Core.ServiceReference1.acquireRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acquireRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text_id;
        
        public acquireRequestBody() {
        }
        
        public acquireRequestBody(string text_id) {
            this.text_id = text_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acquireResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acquireResponse", Namespace="http://lt3serv.ugent.be/", Order=0)]
        public InputLog.Core.ServiceReference1.acquireResponseBody Body;
        
        public acquireResponse() {
        }
        
        public acquireResponse(InputLog.Core.ServiceReference1.acquireResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acquireResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public acquireResponseBody() {
        }
        
        public acquireResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PreProWSChannel : InputLog.Core.ServiceReference1.PreProWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreProWSClient : System.ServiceModel.ClientBase<InputLog.Core.ServiceReference1.PreProWS>, InputLog.Core.ServiceReference1.PreProWS {
        
        public PreProWSClient() {
        }
        
        public PreProWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PreProWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreProWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PreProWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InputLog.Core.ServiceReference1.submitResponse InputLog.Core.ServiceReference1.PreProWS.submit(InputLog.Core.ServiceReference1.submitRequest request) {
            return base.Channel.submit(request);
        }
        
        public string submit(string language, string text) {
            InputLog.Core.ServiceReference1.submitRequest inValue = new InputLog.Core.ServiceReference1.submitRequest();
            inValue.Body = new InputLog.Core.ServiceReference1.submitRequestBody();
            inValue.Body.language = language;
            inValue.Body.text = text;
            InputLog.Core.ServiceReference1.submitResponse retVal = ((InputLog.Core.ServiceReference1.PreProWS)(this)).submit(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InputLog.Core.ServiceReference1.checkResponse InputLog.Core.ServiceReference1.PreProWS.check(InputLog.Core.ServiceReference1.checkRequest request) {
            return base.Channel.check(request);
        }
        
        public string check(string text_id) {
            InputLog.Core.ServiceReference1.checkRequest inValue = new InputLog.Core.ServiceReference1.checkRequest();
            inValue.Body = new InputLog.Core.ServiceReference1.checkRequestBody();
            inValue.Body.text_id = text_id;
            InputLog.Core.ServiceReference1.checkResponse retVal = ((InputLog.Core.ServiceReference1.PreProWS)(this)).check(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        InputLog.Core.ServiceReference1.acquireResponse InputLog.Core.ServiceReference1.PreProWS.acquire(InputLog.Core.ServiceReference1.acquireRequest request) {
            return base.Channel.acquire(request);
        }
        
        public string acquire(string text_id) {
            InputLog.Core.ServiceReference1.acquireRequest inValue = new InputLog.Core.ServiceReference1.acquireRequest();
            inValue.Body = new InputLog.Core.ServiceReference1.acquireRequestBody();
            inValue.Body.text_id = text_id;
            InputLog.Core.ServiceReference1.acquireResponse retVal = ((InputLog.Core.ServiceReference1.PreProWS)(this)).acquire(inValue);
            return retVal.Body.@return;
        }
    }
}
