using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using InputLog.Core.Reporting.ReportTemplate;
using MigraDoc.DocumentObjectModel;
using MigraDoc.DocumentObjectModel.Shapes;
using MigraDoc.DocumentObjectModel.Tables;
using MigraDoc.Rendering;

namespace InputLog.Core.Reporting.Output
{
    /// <summary>
    ///     Formatter used to write a report to a pdf.
    /// </summary>
    public class PdfFormatter : Formatter
    {
        #region Fields

        /// <summary>
        ///     In memory version of the PDF document being constructed.
        /// </summary>
        private Document _document;

        /// <summary>
        ///     Current table, represents the document to which
        ///     we add blocks (rows)
        /// </summary>
        private Table _currentTable;

        /// <summary>
        ///     Current row. Represents a block.
        /// </summary>
        private Row _currentRow;

        /// <summary>
        ///     The cell to which we are adding the elements.
        /// </summary>
        private Cell _currentCell;

        /// <summary>
        ///     The current paragraph to which we are adding a single element's data.
        /// </summary>
        private Paragraph _currentParagraph;

        /// <summary>
        ///     Collection of images to be added to the end of the current block
        /// </summary>
        private Queue<ImageDescription> _imageAppendixQueue;

        /// <summary>
        ///     Structured text that should be prepended to the current block (from template)
        /// </summary>
        private IEnumerable<ReportTemplate.ReportTemplate.StructuredText> _currentBlockPrepend;

        /// <summary>
        ///     Structured text that should be append to the current block. (from template)
        /// </summary>
        private IEnumerable<ReportTemplate.ReportTemplate.StructuredText> _currentBlockAppend;

        /// <summary>
        ///     Label for the current element (from template)
        /// </summary>
        private string _currentValueLabel;

        /// <summary>
        ///     Prepend value for the value. Gets prepended before the label
        /// </summary>
        private string _currentValuePrepend;

        /// <summary>
        ///     Append value for the value. Gets appended after the 'value_id'-value.
        /// </summary>
        private string _currentValueAppend;

        /// <summary>
        ///     Whether the current label should be in bold or not.
        /// </summary>
        private bool _currentValueLabelIsBold;

        /// <summary>
        ///     Introductory txt for current element (from template)
        /// </summary>
        private string _currentElementIntroduction;

        #endregion

        #region Constants

        private double TABLE_WIDTH = 16.5;
        private double COLUMN_WIDTH_LEFT = 3;
        private double COLUMN_WIDTH_RIGHT = 13.5;
        private double PAGENUMBER_OFFSET = 15.5;
        private double LIST_MARGIN_LEFT = 0.5;

        #endregion


        /// <summary>
        ///     Create a new PdfFormatter
        /// </summary>
        public PdfFormatter()
        {
            _document = new Document();
            _imageAppendixQueue = new Queue<ImageDescription>(2);
        }

        #region Report

        /// <summary>
        ///     Clear variables:
        ///     - list of images to append
        ///     Prepare document for writing:
        ///     - Set document info (title, subject, author)
        ///     - Define styles in document
        ///     - Set basic layout information (color)
        ///     Write:
        ///     - Document header.
        /// </summary>
        public override void StartReport(ReportTemplate.ReportTemplate template)
        {
            _imageAppendixQueue.Clear();
            _document.AddSection();

            SetDocumentInfo(template.Title);
            DefineDocumentStyles();
            SetBasicLayout();

            WriteHeaderInfo(template.Title);
            WriteFooterInfo();
        }

        private void SetDocumentInfo(string title)
        {
            _document.Info.Title = title;
            _document.Info.Subject = "Report of participant's Logging Data";
            _document.Info.Author = "Generated by Inputlog";
        }

        private void DefineDocumentStyles()
        {
            var style = _document.Styles["Normal"];
            style.Font.Name = "Calibri";
            style.Font.Size = 11;
            style.ParagraphFormat.Alignment = ParagraphAlignment.Left;
            style.Font.Color = new Color(0x33, 0x33, 0x66);

            style = _document.AddStyle("H1", "Normal");
            style.Font.Size = 17;
            style.Font.Bold = true;
            style.Font.Color = new Color(0x66, 0x00, 0x00);
            style.ParagraphFormat.SpaceAfter = 20;
            style.ParagraphFormat.SpaceBefore = 10;

            style = _document.AddStyle("Appendix-SamePage", "Normal");
            style.Font.Size = 17;
            style.Font.Bold = true;
            style.Font.Color = new Color(0x66, 0x00, 0x00);
            style.ParagraphFormat.SpaceAfter = 20;

            style = _document.AddStyle("Appendix-NewPage", "Appendix-SamePage");
            style.ParagraphFormat.PageBreakBefore = true;

            style = _document.Styles.AddStyle("IntroBlock-Title", "Normal");
            style.Font.Color = new Color(0x66, 0x00, 0x00);
            style = _document.Styles.AddStyle("Block-Title", "Normal");
            style.Font.Bold = true;
            style.Font.Color = new Color(0x66, 0x00, 0x00);

            style = _document.Styles.AddStyle("IntroBlock-Text", "Normal");
            style = _document.Styles.AddStyle("Block-Text", "Normal");
            style = _document.Styles.AddStyle("Block-Text-WithinList", "Normal");
            style.ParagraphFormat.LeftIndent = "0.5cm";

            style = _document.Styles.AddStyle("Block-Text-BulletItem", "Normal");
            style.ParagraphFormat.LeftIndent = "0.5cm";

            // Define footer page-number style
            style = _document.Styles.AddStyle("PageNumber", "Normal");
            style.ParagraphFormat.TabStops.ClearAll();
            style.ParagraphFormat.TabStops.AddTabStop(Unit.FromCentimeter(PAGENUMBER_OFFSET), TabAlignment.Left);

            // Define Bullet list style.
            style = _document.Styles.AddStyle("BulletList", "Normal");
            style.ParagraphFormat.RightIndent = 12;
            style.ParagraphFormat.TabStops.ClearAll();
            style.ParagraphFormat.TabStops.AddTabStop(Unit.FromCentimeter(0.5), TabAlignment.Left);
            style.ParagraphFormat.LeftIndent = "0.5cm";
            style.ParagraphFormat.FirstLineIndent = "-0.5cm";
            style.ParagraphFormat.SpaceAfter = 0;
            style.ParagraphFormat.SpaceBefore = 0;

            // Disclaimer style
            style = _document.Styles.AddStyle("Disclaimer", "Normal");
            style.Font.Size = 7.5;
        }

        private void SetBasicLayout()
        {
            _document.UseCmykColor = true;
        }

        private void WriteHeaderInfo(string title)
        {
            var logo = Properties.Resources.InputLog_Logo;
            var stream = new MemoryStream();
            logo.Save(stream, ImageFormat.Bmp);
            var imageString = _migraDocImageFilenameFromStream(stream);
            var image = _document.LastSection.AddImage(imageString);
            image.RelativeHorizontal = RelativeHorizontal.Margin;
            image.WrapFormat.Style = WrapStyle.TopBottom;
            image.Width = Unit.FromCentimeter(3);
            image.LockAspectRatio = true;
            image.Left = ShapePosition.Left;
            image.Top = ShapePosition.Top;

            var titleParagraph =
                _document.LastSection.AddParagraph(ParseForSessionData(title));
            titleParagraph.Style = "H1";
        }

        private void WriteFooterInfo()
        {
            var section = _document.LastSection;
            section.PageSetup.StartingNumber = 1;

            var paragraph = new Paragraph();
            paragraph.Style = "PageNumber";
            paragraph.AddTab();
            paragraph.AddPageField();
            section.Footers.Primary.Add(paragraph);
        }


        /// <summary>
        ///     Does nothing.
        /// </summary>
        public override void EndReport()
        {
        }

        #endregion


        /// <summary>
        ///     Add table, set column widths.
        /// </summary>
        public override void StartBlocks(int nrOfBlocks)
        {
            // Start Table
            _currentTable = _document.LastSection.AddTable();
            _currentTable.AddColumn(Unit.FromCentimeter(COLUMN_WIDTH_LEFT));
            _currentTable.AddColumn(Unit.FromCentimeter(COLUMN_WIDTH_RIGHT));
        }

        /// <summary>
        ///     From template read:
        ///     - Block append
        ///     - Block prepend
        ///     - Block title
        ///     Make new row, set block title in first cell. Add padding
        ///     CurrentParagraph set to right cell and prepend text added if not empty.
        /// </summary>
        public override void StartBlock(BlockTemplate template)
        {
            _currentBlockAppend = template.Append;
            _currentBlockPrepend = template.Prepend;

            _currentRow = _currentTable.AddRow();
            _currentRow.Format.KeepTogether = false;
            var blockTitleCell = _currentRow.Cells[0];
            _addPaddingToCell(blockTitleCell);
            var blockTitle = blockTitleCell.AddParagraph();
            blockTitle.Style = "Block-Title";
            blockTitle.AddText(ParseForSessionData(template.Title));

            _currentCell = _currentRow.Cells[1];
            _currentCell.Borders.Top.Width = 0.25;
            _currentCell.Borders.Top.Color = new Color(0x33, 0x33, 0x66);
            _addPaddingToCell(_currentCell);

            if (_currentBlockPrepend != null &&
                _currentBlockPrepend.Count() > 0)
                _addStructuredTextToCell(_currentCell, _currentBlockPrepend);
        }

        /// <summary>
        ///     Helper method adds padding to a cell (=paragraph font 8)
        /// </summary>
        private void _addPaddingToCell(Cell cell)
        {
            var padding = cell.AddParagraph(" ");
            padding.Format.Font.Size = 8;
        }

        /// <summary>
        ///     Add structured text to a cell (only prepend or append)
        ///     - Lists
        ///     - Paragraphs
        /// </summary>
        /// <param name="cell">Cell to which we add text</param>
        /// <param name="structuredText">Text (structured) to add to the cell</param>
        private void _addStructuredTextToCell(Cell cell,
            IEnumerable<ReportTemplate.ReportTemplate.StructuredText> structuredText)
        {
            foreach (var textElement in structuredText)
                if (textElement.IsParagraph)
                {
                    var para = cell.AddParagraph(ParseForSessionData(textElement.Content));
                }
                else if (textElement.IsList)
                {
                    foreach (var item in textElement.Items)
                    {
                        var itemPara = cell.AddParagraph(ParseForSessionData(item));
                        MakeIntoBulletedItem(itemPara);
                        itemPara.Style = "BulletList";
                    }
                }
                else
                {
                    Debug.Assert(false, "Unknown structured text type.");
                }
        }

        /// <summary>
        ///     - Add block append
        ///     - Unset block Append & Prepend.
        ///     - Add cell bottom padding and line.
        /// </summary>
        public override void EndBlock()
        {
            if (_currentBlockAppend != null &&
                _currentBlockAppend.Count() > 0)
                _addStructuredTextToCell(_currentCell, _currentBlockAppend);

            _currentBlockPrepend = null;
            _currentBlockAppend = null;

            _addPaddingToCell(_currentCell);
            _currentCell.Borders.Bottom.Width = 0.25;
            _currentCell.Borders.Bottom.Color = new Color(0x33, 0x33, 0x66);
        }

        /// <summary>
        ///     Save all images in queue as appendix.
        /// </summary>
        public override void EndBlocks()
        {
            AddDisclaimer();
            if (_imageAppendixQueue.Count > 0) _addImageAppendices();
        }

        private void AddDisclaimer()
        {
            _currentRow = _currentTable.AddRow();
            _currentCell = _currentRow.Cells[0];
            _addPaddingToCell(_currentCell);
            _currentParagraph = _currentCell.AddParagraph();

            // Load Image
            var cc_image = Properties.Resources.CC_Image;
            var stream = new MemoryStream();
            cc_image.Save(stream, ImageFormat.Bmp);
            var imageString = _migraDocImageFilenameFromStream(stream);
            var image = _currentParagraph.AddImage(imageString);
            image.RelativeHorizontal = RelativeHorizontal.Margin;
            image.WrapFormat.Style = WrapStyle.Through;
            image.Width = Unit.FromCentimeter(2.5);
            image.LockAspectRatio = true;
            image.Left = ShapePosition.Center;
            image.Top = ShapePosition.Center;

            _currentCell = _currentRow.Cells[1];
            _addPaddingToCell(_currentCell);
            _currentParagraph = _currentCell.AddParagraph();
            _currentParagraph.Style = "Disclaimer";

            const string disclaimer =
                "Although much care has been taken to ensure the accuracy, completeness and reliability of the information " +
                "provided in this report, we make no representations or warranties of any kind, express or implied, about the " +
                "completeness, accuracy, reliability or suitability.";

            _currentParagraph.AddText(disclaimer);
        }

        /// <summary>
        ///     Keep track of the nr of elements in current block.
        /// </summary>
        private int _nrOfElements;

        /// <summary>
        ///     Set nr of elements: used for detecting whether a bullet should be used.
        /// </summary>
        public override void StartElements(int nrOfElements)
        {
            _nrOfElements = nrOfElements;
        }

        /// <summary>
        ///     Get introduction & write from template.
        ///     - Set the current paragraph
        /// </summary>
        public override void StartElement(ElementTemplate template)
        {
            _currentElementIntroduction = ParseForSessionData(template.Introduction);
            _currentParagraph = _currentCell.AddParagraph();

            // Bullet if > 1 elements otherwise just line break
            if (_nrOfElements > 1)
            {
                MakeIntoBulletedItem(_currentParagraph);
                _currentParagraph.Style = "BulletList";
            }
            else
            {
                _currentParagraph = _currentCell.AddParagraph();
            }

            WriteIntroduction(_currentElementIntroduction);
        }

        private bool _elementHasIntroduction;

        private void WriteIntroduction(string introduction)
        {
            // Add intro if there isn't one yet and the one specified isn't null
            // add a linebreak.
            if (!_elementHasIntroduction && introduction != null)
            {
                // Non null introduction means we have an empty introduction and overwrite the default
                _elementHasIntroduction = true;

                // But we really only write it if the introduction is not empty, otherwise it's just 
                // an overwrite of the default.
                if (introduction != string.Empty)
                {
                    _currentParagraph.AddText(introduction);
                    _currentParagraph.AddLineBreak();
                }
            }
        }

        /// <summary>
        ///     Unset element introduction
        /// </summary>
        public override void EndElement()
        {
            _currentElementIntroduction = null;
            _elementHasIntroduction = false;
        }

        /// <summary>
        ///     Unset nr of elements
        /// </summary>
        public override void EndElements()
        {
            _nrOfElements = 0;
        }

        /// <summary>
        ///     Specifies how many values we've already added to
        ///     this element.
        /// </summary>
        public int _valueIndex;

        /// <summary>
        ///     Reset the valueIndex to 0
        /// </summary>
        public override void StartValues(int nrOfValues)
        {
            base.StartValues(nrOfValues);
            _valueIndex = 0;
        }

        /// <summary>
        ///     Save value templated information:
        ///     - label
        ///     - prepend
        ///     - append
        ///     - label is bold?
        /// </summary>
        public override void StartValue(ValueTemplate template)
        {
            base.StartValue(template);

            _currentValueAppend = ParseForSessionData(template.Append);
            _currentValuePrepend = ParseForSessionData(template.Prepend);
            _currentValueLabel = template.Label;
            _currentValueLabelIsBold = template.IsBold;
        }

        /// <summary>
        ///     Helper function that sets a paragraph as an enumeration
        ///     within a list.
        /// </summary>
        private void MakeIntoBulletedItem(Paragraph paragraph)
        {
            var listInfo = new ListInfo
            {
                ListType = ListType.BulletList3
            };
            paragraph.Format.ListInfo = listInfo;
        }

        #region Content Methods

        /// <summary>
        ///     Add a labeled value (non-graphical element).
        /// </summary>
        /// <param name="defaultLabel">Default label for the value</param>
        /// <param name="value">Value as a string.</param>
        /// <param name="intro">Default introduction for the element - not from template</param>
        public override void AddLabeledValue(string defaultLabel, string value, string intro = null)
        {
            // Writes the introduction of the first value within the element, 
            // But only writes the introduction if no introduction has been written yet.
            // If the element specified an introduction, no other text will be added.
            if (_valueIndex == 0) WriteIntroduction(ParseForSessionData(intro));

            var label = _currentValueLabel ?? defaultLabel;
            label = ParseForSessionData(label);

            // Add prepend
            if (!string.IsNullOrEmpty(_currentValuePrepend)) _currentParagraph.AddText(_currentValuePrepend);

            // If label is bold, set the fText value to Bold
            // If the label is an empty string, don't write anything.
            if (!string.IsNullOrEmpty(label))
            {
                var fText = _currentParagraph.AddFormattedText(label);
                if (_currentValueLabelIsBold) fText.Bold = true;
            }

            // Add value.
            _currentParagraph.AddText(value);

            // Add append
            if (!string.IsNullOrEmpty(_currentValueAppend)) _currentParagraph.AddText(_currentValueAppend);
        }

        /// <summary>
        ///     Add a labeled image to the report. The image will be added in place unless the images
        ///     is a full page image, in which case it will be added to the end of the report in
        ///     an appendix.
        /// </summary>
        /// <param name="defaultLabel">Label of the image.</param>
        /// <param name="imageStream">Image contents</param>
        /// <param name="intro">Default introduction for the element - not from template</param>
        /// <param name="fullPage">True if the image is a full page image, false if not.</param>
        public override void AddLabeledImage(string defaultLabel, Stream imageStream, string intro = null,
            bool fullPage = false)
        {
            // Writes the introduction of the first value within the element, 
            // But only writes the introduction if no introduction has been written yet.
            // If the element specified an introduction, no other text will be added.
            if (_valueIndex == 0) WriteIntroduction(ParseForSessionData(intro));

            var label = _currentValueLabel == null
                ? defaultLabel
                : _currentValueLabel;
            label = ParseForSessionData(label);

            // Add prepend
            if (!string.IsNullOrEmpty(_currentValuePrepend)) _currentParagraph.AddText(_currentValuePrepend);

            // Set bold if required.
            if (!string.IsNullOrEmpty(label))
            {
                var fText = _currentParagraph.AddFormattedText(label);
                if (_currentValueLabelIsBold) fText.Bold = true;
            }

            // Add append
            if (!string.IsNullOrEmpty(_currentValueAppend)) _currentParagraph.AddText(_currentValueAppend);

            // Add image now, or if it's full page just add an appendix reference
            // and add it later.
            if (fullPage)
            {
                var descr = new ImageDescription(label, imageStream);
                _imageAppendixQueue.Enqueue(descr);

                var appendixNr = _imageAppendixQueue.Count;
                _currentParagraph.AddLineBreak();
                _currentParagraph.AddText("See appendix " + appendixNr);
            }
            else
            {
                var image = _currentCell.AddImage(_migraDocImageFilenameFromStream(imageStream));
                image.LockAspectRatio = true;
                image.Width = Unit.FromCentimeter(COLUMN_WIDTH_RIGHT);
            }
        }


        /// <summary>
        ///     Add the images in the appendixQueue as appendices.
        ///     Each image is on its own separate page.
        /// </summary>
        private void _addImageAppendices()
        {
            var count = 0;
            while (_imageAppendixQueue.Count > 0)
            {
                var descr = _imageAppendixQueue.Dequeue();
                count += 1;

                var appendixTitle = "Appendix " + count + ": " + descr.label;
                _currentParagraph = _document.LastSection.AddParagraph(appendixTitle);

                // Put two appendices on the same page. First one new page, second one same page, and so on...
                if (count % 2 == 0)
                    _currentParagraph.Style = "Appendix-SamePage";
                else
                    _currentParagraph.Style = "Appendix-NewPage";

                // Add image
                _currentParagraph = _document.LastSection.AddParagraph();
                _currentParagraph.Format.LeftIndent = Unit.FromCentimeter(-1);
                var image = _currentParagraph.AddImage(_migraDocImageFilenameFromStream(descr.image));
                image.LockAspectRatio = true;
                image.Width = "19cm";
            }
        }

        /// <summary>
        ///     Creates a MigraDoc 'filename' which is a base64 encoded image without it
        ///     having to be an actual filename. The 'filename' is created from stream
        ///     containing the image data.
        /// </summary>
        /// <param name="imageStream">Stream containing the image data</param>
        /// <returns></returns>
        private string _migraDocImageFilenameFromStream(Stream imageStream)
        {
            var count = (int) imageStream.Length;
            var image = new byte[count];
            imageStream.Seek(0, SeekOrigin.Begin);
            imageStream.Read(image, 0, count);

            const string prefix = "base64:";
            return prefix + Convert.ToBase64String(image);
        }

        #endregion

        public override void WriteToFile(string filepath)
        {
            var pdfRenderer = new PdfDocumentRenderer(true) {Document = _document};
            pdfRenderer.RenderDocument();
            pdfRenderer.PdfDocument.Save(filepath);
        }

        public override void WriteToStream(Stream stream)
        {
            var pdfRenderer = new PdfDocumentRenderer(true) {Document = _document};
            pdfRenderer.RenderDocument();
            pdfRenderer.PdfDocument.Save(stream);
        }

        public override string GetExtension()
        {
            return "pdf";
        }

        public override string GetAffix()
        {
            return string.Empty;
        }


        /// <summary>
        ///     Image description
        /// </summary>
        private class ImageDescription
        {
            public string label { get; }
            public Stream image { get; }

            public ImageDescription(string label, Stream image)
            {
                this.label = label;
                this.image = image;
            }
        }
    }
}