//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Tabs.Record {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Record_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Record_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI.Tabs.Record.Record.Resources", typeof(Record_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos; already exists, do you want overwrite the file?.
        /// </summary>
        internal static string _already_exists_do_you_want_overwrite_the_file {
            get {
                return ResourceManager.GetString("_already_exists_do_you_want_overwrite_the_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  segments.
        /// </summary>
        internal static string _segments {
            get {
                return ResourceManager.GetString("_segments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Keyboard Missing.
        /// </summary>
        internal static string Chinese_Keyboard_Missing {
            get {
                return ResourceManager.GetString("Chinese_Keyboard_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Logging only supports the Sogou Input keyboard. .
        /// </summary>
        internal static string Chinese_Logging_only_supports_the_SogouInput_keyboard_ {
            get {
                return ResourceManager.GetString("Chinese_Logging_only_supports_the_SogouInput_keyboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputLog - Overwrite file?.
        /// </summary>
        internal static string InputLog__Overwrite_file {
            get {
                return ResourceManager.GetString("InputLog__Overwrite_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputLog: Error.
        /// </summary>
        internal static string InputLog_Error {
            get {
                return ResourceManager.GetString("InputLog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keystroke logging outside the main Word document..
        /// </summary>
        internal static string No_keystroke_logging_outside_the_main_Word_document {
            get {
                return ResourceManager.GetString("No_keystroke_logging_outside_the_main_Word_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file was split into .
        /// </summary>
        internal static string Output_file_was_split_into_ {
            get {
                return ResourceManager.GetString("Output_file_was_split_into_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the Participant&apos;s name.
        /// </summary>
        internal static string Please_fill_in_the_Participants_name {
            get {
                return ResourceManager.GetString("Please_fill_in_the_Participants_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install from https://pinyin.sogou.com, then select the Chinese keyboard..
        /// </summary>
        internal static string Please_install_from_httpspinyinsogoucom_then_select_the_Chinese_keyboard {
            get {
                return ResourceManager.GetString("Please_install_from_httpspinyinsogoucom_then_select_the_Chinese_keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        internal static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted Logging.
        /// </summary>
        internal static string Restricted_Logging {
            get {
                return ResourceManager.GetString("Restricted_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmenting Finished.
        /// </summary>
        internal static string Segmenting_Finished {
            get {
                return ResourceManager.GetString("Segmenting_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        internal static string Stop_Recording {
            get {
                return ResourceManager.GetString("Stop_Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination file &apos;.
        /// </summary>
        internal static string The_destination_file_ {
            get {
                return ResourceManager.GetString("The_destination_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create output directory.
        /// </summary>
        internal static string Unable_to_create_output_directory {
            get {
                return ResourceManager.GetString("Unable_to_create_output_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start logging: .
        /// </summary>
        internal static string Unable_to_start_logging_ {
            get {
                return ResourceManager.GetString("Unable_to_start_logging_", resourceCulture);
            }
        }
    }
}
