//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Workspace {
            get {
                return ((string)(this["Workspace"]));
            }
            set {
                this["Workspace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SeperateMouseMovements {
            get {
                return ((bool)(this["SeperateMouseMovements"]));
            }
            set {
                this["SeperateMouseMovements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public ulong MouseMovementPauseThreshold {
            get {
                return ((ulong)(this["MouseMovementPauseThreshold"]));
            }
            set {
                this["MouseMovementPauseThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("notepad")]
        public string Record_OpenWith {
            get {
                return ((string)(this["Record_OpenWith"]));
            }
            set {
                this["Record_OpenWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Record_AnalysisDoneChoice {
            get {
                return ((int)(this["Record_AnalysisDoneChoice"]));
            }
            set {
                this["Record_AnalysisDoneChoice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>VK_LSHIFT</string>
  <string>VK_RSHIFT</string>
  <string>VK_LCONTROL</string>
  <string>VK_RCONTROL</string>
  <string>VK_SHIFT</string>
  <string>VK_CONTROL</string>
  <string>VK_LMENU</string>
  <string>VK_MENU</string>
  <string>VK_LEFT</string>
  <string>VK_RIGHT</string>
  <string>VK_UP</string>
  <string>VK_DOWN</string>
  <string>VK_HOME</string>
  <string>VK_END</string>
  <string>VK_PAUSE</string>
  <string>VK_ESCAPE</string>
  <string>VK_PRINT</string>
  <string>VK_NUMLOCK</string>
  <string>VK_SCROLL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GroupedKeysList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GroupedKeysList"]));
            }
            set {
                this["GroupedKeysList"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int BalloonTipTimeOut {
            get {
                return ((int)(this["BalloonTipTimeOut"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHide {
            get {
                return ((bool)(this["AutoHide"]));
            }
            set {
                this["AutoHide"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sessionstate")]
        public string SessionStateFileName {
            get {
                return ((string)(this["SessionStateFileName"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Analysis_RecognizeDoubleClicks {
            get {
                return ((bool)(this["Analysis_RecognizeDoubleClicks"]));
            }
            set {
                this["Analysis_RecognizeDoubleClicks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long Analysis_DoubleClickThreshold {
            get {
                return ((long)(this["Analysis_DoubleClickThreshold"]));
            }
            set {
                this["Analysis_DoubleClickThreshold"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int PlayIntervalMin {
            get {
                return ((int)(this["PlayIntervalMin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PlayIntervalMax {
            get {
                return ((int)(this["PlayIntervalMax"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int PlayBarValue {
            get {
                return ((int)(this["PlayBarValue"]));
            }
            set {
                this["PlayBarValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output")]
        public string Analysis_DestinationSubdirectory {
            get {
                return ((string)(this["Analysis_DestinationSubdirectory"]));
            }
            set {
                this["Analysis_DestinationSubdirectory"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("idfx")]
        public string Logfile_extension {
            get {
                return ((string)(this["Logfile_extension"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_original")]
        public string Original_doc_appendix {
            get {
                return ((string)(this["Original_doc_appendix"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StorePersonalMaxima {
            get {
                return ((bool)(this["StorePersonalMaxima"]));
            }
            set {
                this["StorePersonalMaxima"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1,2")]
        public string Record_EventSelection {
            get {
                return ((string)(this["Record_EventSelection"]));
            }
            set {
                this["Record_EventSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1")]
        public string Record_PluginSelection {
            get {
                return ((string)(this["Record_PluginSelection"]));
            }
            set {
                this["Record_PluginSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Record_LogFormat {
            get {
                return ((int)(this["Record_LogFormat"]));
            }
            set {
                this["Record_LogFormat"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>VK_LSHIFT</string>
  <string>VK_RSHIFT</string>
  <string>VK_LCONTROL</string>
  <string>VK_RCONTROL</string>
  <string>VK_SHIFT</string>
  <string>VK_CONTROL</string>
  <string>VK_LMENU</string>
  <string>VK_MENU</string>
  <string>VK_LEFT</string>
  <string>VK_RIGHT</string>
  <string>VK_UP</string>
  <string>VK_DOWN</string>
  <string>VK_HOME</string>
  <string>VK_END</string>
  <string>VK_PAUSE</string>
  <string>VK_ESCAPE</string>
  <string>VK_PRINT</string>
  <string>VK_NUMLOCK</string>
  <string>VK_SCROLL</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DefaultGroupedKeysList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DefaultGroupedKeysList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HighPrecision {
            get {
                return ((bool)(this["HighPrecision"]));
            }
            set {
                this["HighPrecision"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string StorePersonalOptima {
            get {
                return ((string)(this["StorePersonalOptima"]));
            }
            set {
                this["StorePersonalOptima"] = value;
            }
        }
    }
}
